pipelines:
  default:
    - parallel:
        - step:
            name: Unit tests
            image: node:12.18-alpine
            caches:
              - node
            script:
              - npm install
              - npm run test:unit
        - step:
            name: Snapshot tests
            image: buildkite/puppeteer:v3.0.4
            caches:
              - node
            script:
              - apt-get update && apt-get -y install procps
              - npm install
              - npm run test:snapshot
            artifacts:
              - test/**/__diff_output__/*.png
