definitions:
  steps:
    - step: &unit-tests
        name: Unit tests
        image: node:12.18-alpine
        script:
          - npm install
          - npm run test:unit

    - step: &snapshot-tests
        name: Snapshot tests
        image: buildkite/puppeteer:v3.0.4
        script:
          - apt-get update && apt-get -y install procps
          - npm install
          - npm run test:snapshot
        artifacts:
          - test/**/__diff_output__/*.png

    - step: &publish-dsm
        name: Publish InVision DSM
        image: node:12.18-alpine
        script:
          - npm install
          - npm run dsm:publish

pipelines:
  default:
    - parallel: &run-tests
        - step: *unit-tests
        - step: *snapshot-tests

  branches:
    master:
      - parallel: *run-tests
      - step: *publish-dsm
