image: buildkite/puppeteer:v3.0.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
        artifacts:
          - test/**/__diff_output__/*.png
