version: '3.7'

services:
  test:
    build: .
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
  test-update:
    build: .
    command: npm run test:snapshot:update
    volumes:
      - .:/app
      - /app/node_modules
